"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AndroidVersion:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AndroidVersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AndroidVersion.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AndroidVersion_NONE: _AndroidVersion.ValueType  # 0
    V4_0: _AndroidVersion.ValueType  # 15
    V4_1: _AndroidVersion.ValueType  # 16
    V4_2: _AndroidVersion.ValueType  # 17
    V4_3: _AndroidVersion.ValueType  # 18
    V4_4: _AndroidVersion.ValueType  # 19
    V4_4W: _AndroidVersion.ValueType  # 20
    V5_0: _AndroidVersion.ValueType  # 21
    V5_1: _AndroidVersion.ValueType  # 22
    V6_0: _AndroidVersion.ValueType  # 23
    V7_0: _AndroidVersion.ValueType  # 24
    V7_1: _AndroidVersion.ValueType  # 25
    V8_0: _AndroidVersion.ValueType  # 26
    V8_1: _AndroidVersion.ValueType  # 27
    V9_0: _AndroidVersion.ValueType  # 28
    V10_0: _AndroidVersion.ValueType  # 29
    V11_0: _AndroidVersion.ValueType  # 30
    V12_0: _AndroidVersion.ValueType  # 31

class AndroidVersion(_AndroidVersion, metaclass=_AndroidVersionEnumTypeWrapper): ...

AndroidVersion_NONE: AndroidVersion.ValueType  # 0
V4_0: AndroidVersion.ValueType  # 15
V4_1: AndroidVersion.ValueType  # 16
V4_2: AndroidVersion.ValueType  # 17
V4_3: AndroidVersion.ValueType  # 18
V4_4: AndroidVersion.ValueType  # 19
V4_4W: AndroidVersion.ValueType  # 20
V5_0: AndroidVersion.ValueType  # 21
V5_1: AndroidVersion.ValueType  # 22
V6_0: AndroidVersion.ValueType  # 23
V7_0: AndroidVersion.ValueType  # 24
V7_1: AndroidVersion.ValueType  # 25
V8_0: AndroidVersion.ValueType  # 26
V8_1: AndroidVersion.ValueType  # 27
V9_0: AndroidVersion.ValueType  # 28
V10_0: AndroidVersion.ValueType  # 29
V11_0: AndroidVersion.ValueType  # 30
V12_0: AndroidVersion.ValueType  # 31
global___AndroidVersion = AndroidVersion

class _LocationProvider:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LocationProviderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LocationProvider.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LocationProvider_NONE: _LocationProvider.ValueType  # 0
    """Treat as random"""
    GPS: _LocationProvider.ValueType  # 1
    NETWORK: _LocationProvider.ValueType  # 2
    PASSIVE: _LocationProvider.ValueType  # 3

class LocationProvider(_LocationProvider, metaclass=_LocationProviderEnumTypeWrapper): ...

LocationProvider_NONE: LocationProvider.ValueType  # 0
"""Treat as random"""
GPS: LocationProvider.ValueType  # 1
NETWORK: LocationProvider.ValueType  # 2
PASSIVE: LocationProvider.ValueType  # 3
global___LocationProvider = LocationProvider

@typing_extensions.final
class AndroidID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___AndroidID = AndroidID

@typing_extensions.final
class GPSLocation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LONGITUDE_FIELD_NUMBER: builtins.int
    LATITUDE_FIELD_NUMBER: builtins.int
    ALTITUDE_FIELD_NUMBER: builtins.int
    PROVIDER_FIELD_NUMBER: builtins.int
    longitude: builtins.float
    latitude: builtins.float
    altitude: builtins.float
    provider: global___LocationProvider.ValueType
    def __init__(
        self,
        *,
        longitude: builtins.float = ...,
        latitude: builtins.float = ...,
        altitude: builtins.float = ...,
        provider: global___LocationProvider.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["altitude", b"altitude", "latitude", b"latitude", "longitude", b"longitude", "provider", b"provider"]) -> None: ...

global___GPSLocation = GPSLocation

@typing_extensions.final
class Locale(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LANGUAGE_FIELD_NUMBER: builtins.int
    COUNTRYISO_FIELD_NUMBER: builtins.int
    language: builtins.str
    countryISO: builtins.str
    def __init__(
        self,
        *,
        language: builtins.str = ...,
        countryISO: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["countryISO", b"countryISO", "language", b"language"]) -> None: ...

global___Locale = Locale

@typing_extensions.final
class SIMCard(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PHONENUMBER_FIELD_NUMBER: builtins.int
    MCC_FIELD_NUMBER: builtins.int
    MNC_FIELD_NUMBER: builtins.int
    CARRIER_FIELD_NUMBER: builtins.int
    COUNTRYISO_FIELD_NUMBER: builtins.int
    COUNTRYCODE_FIELD_NUMBER: builtins.int
    IMEI_FIELD_NUMBER: builtins.int
    MEID_FIELD_NUMBER: builtins.int
    phoneNumber: builtins.str
    """With or without country code?"""
    MCC: builtins.str
    """Provider and country information"""
    MNC: builtins.str
    carrier: builtins.str
    countryISO: builtins.str
    countryCode: builtins.str
    @property
    def imei(self) -> global___IMEI: ...
    @property
    def meid(self) -> global___MEID: ...
    def __init__(
        self,
        *,
        phoneNumber: builtins.str = ...,
        MCC: builtins.str = ...,
        MNC: builtins.str = ...,
        carrier: builtins.str = ...,
        countryISO: builtins.str = ...,
        countryCode: builtins.str = ...,
        imei: global___IMEI | None = ...,
        meid: global___MEID | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["imei", b"imei", "meid", b"meid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["MCC", b"MCC", "MNC", b"MNC", "carrier", b"carrier", "countryCode", b"countryCode", "countryISO", b"countryISO", "imei", b"imei", "meid", b"meid", "phoneNumber", b"phoneNumber"]) -> None: ...

global___SIMCard = SIMCard

@typing_extensions.final
class IMEI(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAC_FIELD_NUMBER: builtins.int
    IMEI_FIELD_NUMBER: builtins.int
    TAC: builtins.str
    imei: builtins.str
    """src: https://en.wikipedia.org/wiki/International_Mobile_Equipment_Identity
    AA	-	BB	BB	BB	-	CC	CC	CC	D
    Where AA and BB = TAC, CC = serial (randomized) and D = Luhn validation
    """
    def __init__(
        self,
        *,
        TAC: builtins.str = ...,
        imei: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["TAC", b"TAC", "imei", b"imei"]) -> None: ...

global___IMEI = IMEI

@typing_extensions.final
class MEID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REGIONCODE_FIELD_NUMBER: builtins.int
    MANUFACTURERCODE_FIELD_NUMBER: builtins.int
    MEID_FIELD_NUMBER: builtins.int
    RegionCode: builtins.str
    ManufacturerCode: builtins.str
    meid: builtins.str
    """src: https://en.wikipedia.org/wiki/Mobile_equipment_identifier
    R R	X	X	X	X	X	X	Z	Z	Z	Z	Z	Z	C
    Where R = region, X = manufacturer, Z = serial (randomized) and C = Luhn validation
    """
    def __init__(
        self,
        *,
        RegionCode: builtins.str = ...,
        ManufacturerCode: builtins.str = ...,
        meid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ManufacturerCode", b"ManufacturerCode", "RegionCode", b"RegionCode", "meid", b"meid"]) -> None: ...

global___MEID = MEID

@typing_extensions.final
class MAC(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUI_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    OUI: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        OUI: builtins.str = ...,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["OUI", b"OUI", "address", b"address"]) -> None: ...

global___MAC = MAC

@typing_extensions.final
class Timezone(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """IANA standard"""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___Timezone = Timezone

@typing_extensions.final
class DeviceSoftware(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class SoftwareMetaDataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing_extensions.final
    class AppMetaDataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SOFTWAREMETADATA_FIELD_NUMBER: builtins.int
    APPMETADATA_FIELD_NUMBER: builtins.int
    @property
    def softwareMetaData(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def appMetaData(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """app package : version string"""
    def __init__(
        self,
        *,
        softwareMetaData: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        appMetaData: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["appMetaData", b"appMetaData", "softwareMetaData", b"softwareMetaData"]) -> None: ...

global___DeviceSoftware = DeviceSoftware

@typing_extensions.final
class Device(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    LOCALE_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    MANUFACTURER_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    PRODUCT_FIELD_NUMBER: builtins.int
    BUILD_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    INCREMENTALVERSION_FIELD_NUMBER: builtins.int
    DPI_FIELD_NUMBER: builtins.int
    RESOLUTIONHORIZONTAL_FIELD_NUMBER: builtins.int
    RESOLUTIONVERTICAL_FIELD_NUMBER: builtins.int
    ABILIST_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    TIMEZONE_FIELD_NUMBER: builtins.int
    SIMSLOTS_FIELD_NUMBER: builtins.int
    MACADDRESS_FIELD_NUMBER: builtins.int
    SOFTWARE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> global___AndroidID: ...
    @property
    def locale(self) -> global___Locale: ...
    version: global___AndroidVersion.ValueType
    device: builtins.str
    manufacturer: builtins.str
    model: builtins.str
    product: builtins.str
    build: builtins.str
    type: builtins.str
    tags: builtins.str
    incrementalVersion: builtins.str
    DPI: builtins.int
    resolutionHorizontal: builtins.int
    resolutionVertical: builtins.int
    @property
    def abiList(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def location(self) -> global___GPSLocation: ...
    @property
    def timezone(self) -> global___Timezone: ...
    @property
    def simSlots(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SIMCard]:
        """Dual SIM compatibility"""
    @property
    def macAddress(self) -> global___MAC: ...
    @property
    def software(self) -> global___DeviceSoftware: ...
    def __init__(
        self,
        *,
        id: global___AndroidID | None = ...,
        locale: global___Locale | None = ...,
        version: global___AndroidVersion.ValueType = ...,
        device: builtins.str = ...,
        manufacturer: builtins.str = ...,
        model: builtins.str = ...,
        product: builtins.str = ...,
        build: builtins.str = ...,
        type: builtins.str = ...,
        tags: builtins.str = ...,
        incrementalVersion: builtins.str = ...,
        DPI: builtins.int = ...,
        resolutionHorizontal: builtins.int = ...,
        resolutionVertical: builtins.int = ...,
        abiList: collections.abc.Iterable[builtins.str] | None = ...,
        location: global___GPSLocation | None = ...,
        timezone: global___Timezone | None = ...,
        simSlots: collections.abc.Iterable[global___SIMCard] | None = ...,
        macAddress: global___MAC | None = ...,
        software: global___DeviceSoftware | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id", b"id", "locale", b"locale", "location", b"location", "macAddress", b"macAddress", "software", b"software", "timezone", b"timezone"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["DPI", b"DPI", "abiList", b"abiList", "build", b"build", "device", b"device", "id", b"id", "incrementalVersion", b"incrementalVersion", "locale", b"locale", "location", b"location", "macAddress", b"macAddress", "manufacturer", b"manufacturer", "model", b"model", "product", b"product", "resolutionHorizontal", b"resolutionHorizontal", "resolutionVertical", b"resolutionVertical", "simSlots", b"simSlots", "software", b"software", "tags", b"tags", "timezone", b"timezone", "type", b"type", "version", b"version"]) -> None: ...

global___Device = Device
